name: Update README Image Sequence

on:
  workflow_dispatch:
  schedule:
  - cron: '0 2 * * *'

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@latest

      - name: Set up Python
        uses: actions/setup-python@latest
        with:
          python-version: '3.x'

      - name:  Run update script to select next random image
        run: python update_image.py

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@latest
        with:
          author_name: TheKingTermux
          author_email: 50316075+TheKingTermux@users.noreply.github.com
          message: "Otomatis: Update path gambar dan status acak di README.md"
          add: 'README.md status.json' 
